

spring:
  name: vittoriodemo1
  datasource:
    url: jdbc:mysql://localhost:3306/biblioteca?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Vittorio19
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #none
    show-sql: true